root = "."
tmp_dir = "tmp"

[build]
  args_bin = ["serve"]
  bin = "./tmp/main"
  cmd = "time -f 'Took %E' go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "pb_data", "node_modules", "migrations", "ui"]
  exclude_file = ["README.md", "tailwind.config.js"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  # Enable live-reloading on the browser.
  enabled = true
  proxy_port = 8080
  app_port = 8090

[screen]
  clear_on_rebuild = false
  keep_scroll = true

